# Generated by Django 4.2.7 on 2023-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_already_exists',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
