# Generated by Django 4.2.7 on 2024-03-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0002_alter_client_client_already_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='company',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_already_exists',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
