# Generated by Django 4.2.7 on 2024-04-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0003_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_due_date',
            field=models.DateField(default=False),
        ),
    ]
