# Generated by Django 4.2.7 on 2024-04-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0004_alter_order_order_date_alter_order_order_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='total_spent',
        ),
    ]
