# Generated by Django 4.2.7 on 2024-03-18 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0006_client_total_spent_currency_alter_client_total_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
