# Generated by Django 4.2.7 on 2024-03-19 05:29

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0007_alter_order_order_date_alter_order_order_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='security_deposit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
    ]
