# Generated by Django 4.2.7 on 2024-03-20 03:24

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0008_alter_order_security_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_cost_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quoted_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='security_deposit_currency',
        ),
        migrations.AlterField(
            model_name='client',
            name='total_spent_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
