# Generated by Django 4.2.7 on 2024-03-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0009_remove_order_estimated_cost_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='total_spent_currency',
        ),
        migrations.AlterField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
