# Generated by Django 4.2.7 on 2023-12-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
    ]
