# Generated by Django 4.2.7 on 2023-12-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipToAddressLookup',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('state_short', models.CharField(max_length=2)),
                ('state_long', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('timezone', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
