# Generated by Django 4.2.7 on 2023-12-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ziptoaddresslookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziptoaddresslookup',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
