# Generated by Django 4.2.7 on 2023-12-23 01:02

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ziptoaddresslookup_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
