# Generated by Django 4.2.7 on 2024-01-12 05:10

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, error_messages={'invalid': 'Enter a zip code in the format XXXXX.'}, max_length=10, null=True),
        ),
    ]
