# Generated by Django 4.2.7 on 2023-12-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
