# Generated by Django 4.2.7 on 2024-03-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
