# Generated by Django 4.2.7 on 2024-03-31 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('accounts', '0015_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer', to_field='id'),
        ),
    ]
